;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="PlayerAnim.State.Attacking",DevComment="Currently used for melee attacks")
+GameplayTagList=(Tag="PlayerAnim.State.IdleWalkRunBlend",DevComment="")
+GameplayTagList=(Tag="PlayerAnim.State.Idling",DevComment="Only for OT idling")

