[/Script/EngineSettings.GameMapsSettings]
; Force a blank map to bypass loading heavy assets on startup
GameDefaultMap=/Engine/Maps/Templates/Blank/Blank
EditorStartupMap=/Engine/Maps/Templates/Blank/Blank

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX11
D3D12.AllowDX12=False
; Strictly stick to SM5
-D3D12TargetedShaderFormats=PCD3D_SM6
+D3D11TargetedShaderFormats=PCD3D_SM5
Compiler=Default
bGenerateNaniteFallbackMeshes=True

[/Script/Engine.RendererSettings]
r.Nanite=False
r.Nanite.ProjectEnabled=False
r.Lumen.Allow=False
r.DynamicGlobalIlluminationMethod=0
r.ReflectionMethod=0
r.Shadow.Virtual.Enable=0
r.GenerateMeshDistanceFields=False
r.MeshUVPrioritizer.Allow=False

r.DefaultFeature.AmbientOcclusion=False
r.DefaultFeature.Bloom=False
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.LensFlare=False
r.DefaultFeature.AutoExposure=False
r.TonemapperFilm=0

r.AntiAliasingMethod=1
r.TemporalAA.Upsampling=False
r.ScreenPercentage=66.0

r.ForwardShading=True
r.SceneColorFormat=2
r.Mobile.EnableNoPrecomputedLightingCSMShader=True

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
; Fix: Changed SM6 to SM5 to match your hardware's capabilities
-TargetedRHIs=SF_VULKAN_SM6
+TargetedRHIs=SF_VULKAN_SM5
bGenerateNaniteFallbackMeshes=False

[/Script/Engine.UserInterfaceSettings]
bAuthorizeAutomaticWidgetVariableCreation=False
FontDPIPreset=Standard
FontDPI=72

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_BlankBP",NewGameName="/Script/MoveTest")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_BlankBP",NewGameName="/Script/MoveTest")

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=7110B0C94ACCB89C07F3E7864B495610
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

